'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Trust

    Partial Public Class Ms_FundingCosts
        Public Property FundingCost_ID As Integer
        Public Property MonthFrom As Nullable(Of Integer)
        Public Property MonthTo As Nullable(Of Integer)
        Public Property FundingCost As Nullable(Of Decimal)
    
    End Class

End Namespace
