'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class owner
    Public Property owner_id As Integer
    Public Property owner1 As String
    Public Property code As String
    Public Property address_1 As String
    Public Property address_2 As String

End Class
