'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Trust

    Partial Public Class Tr_Calculates
        Public Property Calculate_ID As Integer
        Public Property ProspectCustomerDetail_ID As Nullable(Of Integer)
        Public Property Rent_Location_ID As Nullable(Of Integer)
        Public Property Plat_Location As Nullable(Of Integer)
        Public Property Term_Of_Payment As Nullable(Of Integer)
        Public Property PayMonth As Nullable(Of Integer)
        Public Property Payment_Condition As String
        Public Property Modification As Nullable(Of Decimal)
        Public Property GPS_Cost As Nullable(Of Decimal)
        Public Property GPS_CostPerMonth As Nullable(Of Integer)
        Public Property Agent_Fee As Nullable(Of Decimal)
        Public Property Agent_FeePerMonth As Nullable(Of Integer)
        Public Property Update_OTR As Nullable(Of Decimal)
        Public Property Residual_Value As Nullable(Of Decimal)
        Public Property Residual_ValuePercent As Nullable(Of Decimal)
        Public Property Expedition_Status As String
        Public Property Expedition_Cost As Nullable(Of Decimal)
        Public Property Keur As Nullable(Of Decimal)
        Public Property Update_Diskon As Nullable(Of Decimal)
        Public Property Update_DiskonSystem As Nullable(Of Decimal)
        Public Property Update_DiskonTick As Nullable(Of Boolean)
        Public Property Cost_Price As Nullable(Of Decimal)
        Public Property Up_Front_Fee As Nullable(Of Decimal)
        Public Property Up_Front_Fee_Percent As Nullable(Of Decimal)
        Public Property Other As Nullable(Of Decimal)
        Public Property Efektif_Date As Nullable(Of Date)
        Public Property Replacement_Percent As Nullable(Of Decimal)
        Public Property Replacement As Nullable(Of Decimal)
        Public Property Replacement_Percent_Before As Nullable(Of Decimal)
        Public Property Replacement_Tick As Nullable(Of Boolean)
        Public Property Maintenance_Percent As Nullable(Of Decimal)
        Public Property Maintenance As Nullable(Of Decimal)
        Public Property Maintenance_Percent_Before As Nullable(Of Decimal)
        Public Property Maintenance_Tick As Nullable(Of Boolean)
        Public Property STNK_Percent As Nullable(Of Decimal)
        Public Property STNK As Nullable(Of Decimal)
        Public Property STNK_Percent_Before As Nullable(Of Decimal)
        Public Property STNK_Tick As Nullable(Of Boolean)
        Public Property Overhead_Percent As Nullable(Of Decimal)
        Public Property Overhead As Nullable(Of Decimal)
        Public Property Overhead_Percent_Before As Nullable(Of Decimal)
        Public Property Assurance_Percent As Nullable(Of Decimal)
        Public Property Assurance As Nullable(Of Decimal)
        Public Property Assurance_Percent_Before As Nullable(Of Decimal)
        Public Property Assurance_Tick As Nullable(Of Boolean)
        Public Property AssuranceExtra As Nullable(Of Decimal)
        Public Property Lease_Profit As Nullable(Of Decimal)
        Public Property Lease_Profit_Percent As Nullable(Of Decimal)
        Public Property Depresiasi As Nullable(Of Decimal)
        Public Property Depresiasi_Percent As Nullable(Of Decimal)
        Public Property Funding_Interest As Nullable(Of Decimal)
        Public Property Funding_Interest_Percent As Nullable(Of Decimal)
        Public Property Bid_PricePerMonth As Nullable(Of Decimal)
        Public Property Premium As Nullable(Of Decimal)
        Public Property OJK As Nullable(Of Decimal)
        Public Property SwapRate As Nullable(Of Decimal)
        Public Property Project_Rating As String
        Public Property IRR As Nullable(Of Decimal)
        Public Property Funding_Rate As Nullable(Of Decimal)
        Public Property Spread As Nullable(Of Decimal)
        Public Property Profit As Nullable(Of Decimal)
        Public Property DeviasiBy As Nullable(Of Integer)
        Public Property DeviasiDate As Nullable(Of Date)
        Public Property RemarkDeviasi As String
        Public Property IsEdit As Nullable(Of Boolean)
        Public Property New_Vehicle_Price As Nullable(Of Decimal)
        Public Property Location_Vehicle_ID As Nullable(Of Integer)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property CreatedBy As Nullable(Of Integer)
        Public Property ModifiedDate As Nullable(Of Date)
        Public Property ModifiedBy As Nullable(Of Integer)
        Public Property IsDeleted As Nullable(Of Boolean)
    
        Public Overridable Property Cn_Users As Cn_Users
        Public Overridable Property Cn_Users1 As Cn_Users
        Public Overridable Property Cn_Users2 As Cn_Users
        Public Overridable Property Ms_Citys As Ms_Citys
        Public Overridable Property Ms_Citys1 As Ms_Citys
        Public Overridable Property Ms_Citys2 As Ms_Citys
        Public Overridable Property Tr_CalculateCashFlows As ICollection(Of Tr_CalculateCashFlows) = New HashSet(Of Tr_CalculateCashFlows)
        Public Overridable Property Tr_QuotationDetails As ICollection(Of Tr_QuotationDetails) = New HashSet(Of Tr_QuotationDetails)
    
    End Class

End Namespace
