'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Trust

    Partial Public Class Tr_ContractDetails
        Public Property ContractDetail_ID As Integer
        Public Property Contract_ID As Integer
        Public Property Application_ID As Integer
        Public Property Vehicle_ID As Nullable(Of Integer)
        Public Property DeliveryDate As Nullable(Of Date)
        Public Property StartDate As Nullable(Of Date)
        Public Property EndDate As Nullable(Of Date)
        Public Property Bid_PricePerMonth As Nullable(Of Decimal)
        Public Property Remark As String
        Public Property IsTemporaryCar As Nullable(Of Boolean)
        Public Property IsDelivery As Nullable(Of Boolean)
        Public Property IsInvoiced As Nullable(Of Boolean)
        Public Property IsTotalLossOnly As Nullable(Of Boolean)
        Public Property CreatedDate As Nullable(Of Date)
        Public Property CreatedBy As Nullable(Of Integer)
        Public Property ModifiedDate As Nullable(Of Date)
        Public Property ModifiedBy As Nullable(Of Integer)
        Public Property IsDeleted As Nullable(Of Boolean)
    
        Public Overridable Property Tr_ContractDetailHistorys As ICollection(Of Tr_ContractDetailHistorys) = New HashSet(Of Tr_ContractDetailHistorys)
        Public Overridable Property Tr_Deliverys As ICollection(Of Tr_Deliverys) = New HashSet(Of Tr_Deliverys)
        Public Overridable Property Tr_TemporaryCars As ICollection(Of Tr_TemporaryCars) = New HashSet(Of Tr_TemporaryCars)
        Public Overridable Property Tr_InvoiceDetails As ICollection(Of Tr_InvoiceDetails) = New HashSet(Of Tr_InvoiceDetails)
        Public Overridable Property Tr_TotalLossOnlys As ICollection(Of Tr_TotalLossOnlys) = New HashSet(Of Tr_TotalLossOnlys)
        Public Overridable Property Ms_Vehicles As ICollection(Of Ms_Vehicles) = New HashSet(Of Ms_Vehicles)
        Public Overridable Property Ms_Vehicles1 As Ms_Vehicles
        Public Overridable Property Cn_Users As Cn_Users
        Public Overridable Property Cn_Users1 As Cn_Users
        Public Overridable Property Tr_Applications As Tr_Applications
        Public Overridable Property Tr_SetDeliveryDetails As ICollection(Of Tr_SetDeliveryDetails) = New HashSet(Of Tr_SetDeliveryDetails)
        Public Overridable Property Tr_Contracts As Tr_Contracts
    
    End Class

End Namespace
