'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tr_CalculateCashFlows
    Public Property CalculateCashFlow_ID As Integer
    Public Property Calculate_ID As Nullable(Of Integer)
    Public Property CalculateCashFlow_No As Nullable(Of Integer)
    Public Property CashFlow As Nullable(Of Decimal)
    Public Property Lease_Payment As Nullable(Of Decimal)
    Public Property STNK As Nullable(Of Decimal)
    Public Property Replacement As Nullable(Of Decimal)
    Public Property OverHead As Nullable(Of Decimal)
    Public Property Maintenance As Nullable(Of Decimal)
    Public Property Insurance As Nullable(Of Decimal)
    Public Property Residual_Value As Nullable(Of Decimal)
    Public Property Expedition As Nullable(Of Decimal)
    Public Property Modification As Nullable(Of Decimal)
    Public Property GPS As Nullable(Of Decimal)
    Public Property Agent_Fee As Nullable(Of Decimal)
    Public Property Keur As Nullable(Of Decimal)
    Public Property Profit As Nullable(Of Decimal)
    Public Property CreatedDate As Date
    Public Property CreatedBy As Integer
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property ModifiedBy As Nullable(Of Integer)
    Public Property IsDeleted As Boolean

    Public Overridable Property Cn_Users As Cn_Users
    Public Overridable Property Cn_Users1 As Cn_Users
    Public Overridable Property Tr_Calculates As Tr_Calculates

End Class
