'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Trust

    Partial Public Class Tr_ProspectCustHistorys
        Public Property ProspectCustomerHistory_ID As Integer
        Public Property ProspectCustomer_ID As Integer
        Public Property ProspectCategory_ID As Nullable(Of Integer)
        Public Property Status As String
        Public Property DateTrans As Date
        Public Property Notes As String
        Public Property IsChecked As Nullable(Of Boolean)
        Public Property CheckNote As String
        Public Property CheckedBy As Nullable(Of Integer)
        Public Property CheckedDate As Nullable(Of Date)
        Public Property CreatedDate As Date
        Public Property CreatedBy As Integer
        Public Property ModifiedDate As Nullable(Of Date)
        Public Property ModifiedBy As Nullable(Of Integer)
        Public Property IsDeleted As Boolean
    
        Public Overridable Property Ms_ProspectCategorys As Ms_ProspectCategorys
        Public Overridable Property Cn_Users As Cn_Users
        Public Overridable Property Cn_Users1 As Cn_Users
        Public Overridable Property Cn_Users2 As Cn_Users
        Public Overridable Property Tr_ProspectCusts As Tr_ProspectCusts
    
    End Class

End Namespace
