'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Trust

    Partial Public Class Tr_SetDeliveryDetails
        Public Property SetDeliveryDetail_ID As Integer
        Public Property setDelivery_ID As Nullable(Of Integer)
        Public Property ContractDetail_ID As Nullable(Of Integer)
        Public Property CreatedDate As Date
        Public Property CreatedBy As Integer
        Public Property ModifiedDate As Nullable(Of Date)
        Public Property ModifiedBy As Nullable(Of Integer)
        Public Property Isdeleted As Boolean
    
        Public Overridable Property Cn_Users As Cn_Users
        Public Overridable Property Cn_Users1 As Cn_Users
        Public Overridable Property Tr_ContractDetails As Tr_ContractDetails
        Public Overridable Property Tr_SetDeliveries As Tr_SetDeliveries
    
    End Class

End Namespace
