'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Trust

    Partial Public Class V_Approval
        Public Property ApprovalUser_ID As Integer
        Public Property Approval_ID As Integer
        Public Property User_ID As Integer
        Public Property User_Name As String
        Public Property Approval_Name As String
        Public Property Module_ID As Integer
        Public Property Module_Name As String
        Public Property Level_ID As Integer
        Public Property Limited_Approval As Decimal
        Public Property Level As Nullable(Of Integer)
        Public Property Remark As String
    
    End Class

End Namespace
