'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Trust

    Partial Public Class V_ApplicationPO
        Public Property ProspectCustomerDetail_ID As Integer
        Public Property Qty As Nullable(Of Integer)
    
    End Class

End Namespace
