'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Trust

    Partial Public Class V_ApplicationHD
        Public Property ApplicationHeader_ID As Integer
        Public Property Approval_ID As Nullable(Of Integer)
        Public Property Application_No As String
        Public Property Credit_Rating As String
        Public Property Contracted_by As String
        Public Property Customer_Class As String
        Public Property Authorized_Capital As Nullable(Of Decimal)
        Public Property Authorized_Signer_Name1 As String
        Public Property Authorized_Signer_Position1 As String
        Public Property Authorized_Signer_Name2 As String
        Public Property Authorized_Signer_Position2 As String
        Public Property IntroducedBy As String
        Public Property Outstanding_Balance_Group As Nullable(Of Decimal)
        Public Property Outstanding_Balance_MUL_Group As Nullable(Of Decimal)
        Public Property Outstanding_Balance_Amount As Nullable(Of Decimal)
        Public Property THU As Nullable(Of Integer)
        Public Property RunContractCompany As Nullable(Of Integer)
        Public Property RunContractGroup As Nullable(Of Integer)
        Public Property CreatedDate As Date
        Public Property CreatedBy As Integer
        Public Property ModifiedDate As Nullable(Of Date)
        Public Property ModifiedBy As Nullable(Of Integer)
        Public Property IsDeleted As Boolean
        Public Property Application_ID As Integer
        Public Property IsPO As Boolean
        Public Property POBy As Nullable(Of Integer)
        Public Property IsFillOTR As Nullable(Of Boolean)
        Public Property FillOTRBy As Nullable(Of Integer)
        Public Property QuotationDetail_ID As Integer
        Public Property Payee As String
        Public Property PayeeRemark As String
        Public Property Purchaser As String
        Public Property Purchase_Type As String
        Public Property Rent_Location_ID As Nullable(Of Integer)
        Public Property Plat_Location As Nullable(Of Integer)
        Public Property Payment_Condition As String
        Public Property Modification As Nullable(Of Decimal)
        Public Property GPS_Cost As Nullable(Of Decimal)
        Public Property GPS_CostPerMonth As Nullable(Of Integer)
        Public Property Agent_Fee As Nullable(Of Decimal)
        Public Property Agent_FeePerMonth As Nullable(Of Integer)
        Public Property Update_OTR As Nullable(Of Decimal)
        Public Property Residual_Value As Nullable(Of Decimal)
        Public Property Residual_ValuePercent As Nullable(Of Decimal)
        Public Property Expedition_Cost As Nullable(Of Decimal)
        Public Property Keur As Nullable(Of Decimal)
        Public Property Update_Diskon As Nullable(Of Decimal)
        Public Property Cost_Price As Nullable(Of Decimal)
        Public Property Up_Front_Fee As Nullable(Of Decimal)
        Public Property Up_Front_Fee_Percent As Nullable(Of Decimal)
        Public Property Other As Nullable(Of Decimal)
        Public Property Efektif_Date As Nullable(Of Date)
        Public Property Replacement_Percent As Nullable(Of Decimal)
        Public Property Replacement As Nullable(Of Decimal)
        Public Property Maintenance_Percent As Nullable(Of Decimal)
        Public Property Maintenance As Nullable(Of Decimal)
        Public Property STNK_Percent As Nullable(Of Decimal)
        Public Property STNK As Nullable(Of Decimal)
        Public Property Overhead_Percent As Nullable(Of Decimal)
        Public Property Overhead As Nullable(Of Decimal)
        Public Property Assurance_Percent As Nullable(Of Decimal)
        Public Property Assurance As Nullable(Of Decimal)
        Public Property Lease_Profit As Nullable(Of Decimal)
        Public Property Lease_Profit_Percent As Nullable(Of Decimal)
        Public Property Depresiasi As Nullable(Of Decimal)
        Public Property Depresiasi_Percent As Nullable(Of Decimal)
        Public Property Funding_Interest As Nullable(Of Decimal)
        Public Property Funding_Interest_Percent As Nullable(Of Decimal)
        Public Property Bid_PricePerMonth As Nullable(Of Decimal)
        Public Property IRR As Nullable(Of Decimal)
        Public Property Funding_Rate As Nullable(Of Decimal)
        Public Property Spread As Nullable(Of Decimal)
        Public Property Project_Rating As String
        Public Property Asset_Rating As Nullable(Of Integer)
        Public Property ApprovalApp_ID As Nullable(Of Integer)
        Public Property MakerDate As Nullable(Of Date)
        Public Property MakerBy As Nullable(Of Integer)
        Public Property CheckerDate As Nullable(Of Date)
        Public Property CheckerBy As Nullable(Of Integer)
        Public Property Approval1Date As Nullable(Of Date)
        Public Property Approval1By As Nullable(Of Integer)
        Public Property Approval2Date As Nullable(Of Date)
        Public Property Approval2By As Nullable(Of Integer)
        Public Property Approval3Date As Nullable(Of Date)
        Public Property Approval3By As Nullable(Of Integer)
        Public Property Approval4Date As Nullable(Of Date)
        Public Property Approval4By As Nullable(Of Integer)
        Public Property Approval5Date As Nullable(Of Date)
        Public Property Approval5By As Nullable(Of Integer)
        Public Property StatusRecord As Nullable(Of Integer)
        Public Property Status As String
        Public Property Remark As String
        Public Property Contract_ID As Nullable(Of Integer)
        Public Property Contract_No As String
        Public Property Penerima As String
        Public Property Jabatan As String
        Public Property ContractDetail_ID As Nullable(Of Integer)
        Public Property DeliveryDate As Nullable(Of Date)
        Public Property StartDate As Nullable(Of Date)
        Public Property EndDate As Nullable(Of Date)
        Public Property RemarkContract As String
        Public Property Cost_PriceAll As Nullable(Of Decimal)
        Public Property Term_Of_Payment As Nullable(Of Integer)
        Public Property Code_Open As String
        Public Property Expec_Delivery_Date As Nullable(Of Date)
        Public Property Profit As Nullable(Of Decimal)
    
    End Class

End Namespace
