'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace Trust

    Partial Public Class V_ProspectCustDetails
        Public Property ProspectCustomerDetail_ID As Integer
        Public Property ProspectCustomer_ID As Integer
        Public Property CompanyGroup_Name As String
        Public Property Company_Name As String
        Public Property Customer_ID As Nullable(Of Integer)
        Public Property VehicleExists_ID As Nullable(Of Integer)
        Public Property IsVehicleExists As Boolean
        Public Property Transaction_Type As String
        Public Property Model_ID As Nullable(Of Integer)
        Public Property Normal_Disc As Nullable(Of Decimal)
        Public Property Type As String
        Public Property IsTruck As Nullable(Of Boolean)
        Public Property Gross As Nullable(Of Decimal)
        Public Property GrossApp As Nullable(Of Decimal)
        Public Property OTR_Price As Nullable(Of Decimal)
        Public Property Brand_ID As Nullable(Of Integer)
        Public Property Brand_Name As String
        Public Property Color As String
        Public Property Vehicle As String
        Public Property VehicleType As String
        Public Property Lease_price As Nullable(Of Decimal)
        Public Property Qty As Nullable(Of Integer)
        Public Property RVPersen As Nullable(Of Integer)
        Public Property Keur As Integer
        Public Property Year As Nullable(Of Integer)
        Public Property Lease_long As Nullable(Of Integer)
        Public Property IsMultiCalculated As Nullable(Of Boolean)
        Public Property Amount As Nullable(Of Decimal)
        Public Property Asset_Rating As Nullable(Of Integer)
        Public Property Credit_Rating As String
        Public Property IsCalculate As Nullable(Of Boolean)
        Public Property IsQuotation As Nullable(Of Boolean)
        Public Property Rent_Location_ID As Nullable(Of Integer)
        Public Property FundingCost As Nullable(Of Decimal)
        Public Property Rent_Location As String
        Public Property Bid_PricePerMonth As Nullable(Of Decimal)
        Public Property Residual_Value As Nullable(Of Decimal)
        Public Property QuotationDetail_ID As Nullable(Of Integer)
        Public Property Status As String
        Public Property CreatedBy As Integer
        Public Property Application_ID As Nullable(Of Integer)
        Public Property CreatedDateApp As Nullable(Of Date)
        Public Property Quotation_ID As Nullable(Of Integer)
        Public Property Contract_ID As Nullable(Of Integer)
        Public Property ContractDetail_ID As Nullable(Of Integer)
        Public Property IsFillOTR As Nullable(Of Boolean)
        Public Property QtyAppPO As Nullable(Of Integer)
        Public Property ApplicationPO_No As String
        Public Property ApplicationHeader_ID As Nullable(Of Integer)
        Public Property Calculate_ID As Nullable(Of Integer)
        Public Property PO_No As String
    
    End Class

End Namespace
