'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vehicle_test
    Public Property vehicle_id As Integer
    Public Property owner_id As Integer
    Public Property license_no As String
    Public Property manufacturer_id As Nullable(Of Integer)
    Public Property type As String
    Public Property color As String
    Public Property year As Nullable(Of Integer)
    Public Property chassis_no As String
    Public Property machine_no As String
    Public Property title_no As String
    Public Property serial_no As String
    Public Property registration_no As String
    Public Property registration_expdate As Nullable(Of Date)
    Public Property insurance_no As String
    Public Property discount As Nullable(Of Double)
    Public Property price As Nullable(Of Double)
    Public Property acquisition As Nullable(Of Double)
    Public Property coverage As Nullable(Of Double)
    Public Property comment As String
    Public Property category As Boolean
    Public Property status As Byte
    Public Property remove As Nullable(Of Boolean)
    Public Property date_insurance_start As Nullable(Of Date)
    Public Property date_insurance_end As Nullable(Of Date)
    Public Property date_insurance_mod As Nullable(Of Date)
    Public Property date_book As Nullable(Of Date)
    Public Property date_entered As Date
    Public Property date_modified As Nullable(Of Date)

End Class
